### ISSUE TITLE
Powershell commandline doesn't accept pasting of multi-line documents

### ISSUE THREAD

**Issue by paul-venne-rl** [paullyvenne/paullygpt#2]
It seems the script running in commandline won't accept full pasting of multiline documents, the workaround is the run the script in Visual Studio Code or Powershell IDE..... an alternative method to accepting these kind of pastes are to be worked on.

**Comment by paullyvenne** [comment]
v1.0.10 has a new update which should address the multiline pasting in windows terminal that affects some users. It introduces a 10-50 millisecond delay before the a keypress and the enter key used to submit.
